# Generated by Django 4.2.7 on 2025-12-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('pandit', 'Pandit'), ('lama', 'Lama')], db_index=True, default='user', max_length=10),
        ),
    ]
