# Generated by Django 4.2.7 on 2025-12-16 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ne', models.CharField(blank=True, max_length=100, verbose_name='Name (Nepali)')),
                ('description', models.TextField(blank=True)),
                ('description_ne', models.TextField(blank=True, verbose_name='Description (Nepali)')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, help_text='Default price in NPR', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion_type', models.CharField(choices=[('hindu', 'Hindu Pandit'), ('buddhist', 'Buddhist Lama')], db_index=True, max_length=10)),
                ('experience_years', models.IntegerField(help_text='Years of experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(db_index=True, help_text='Primary service location', max_length=200)),
                ('short_description', models.TextField(help_text='Brief description (English)', max_length=500)),
                ('short_description_ne', models.TextField(blank=True, max_length=500, verbose_name='Short Description (Nepali)')),
                ('price_per_service', models.DecimalField(decimal_places=2, help_text='Base price per service in NPR', max_digits=10)),
                ('verified', models.BooleanField(db_index=True, default=False, help_text='Admin verified provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='providers', to='providers.service')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'db_table': 'service_providers',
                'ordering': ['-verified', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(db_index=True, default=False, help_text='Automatically set when booking confirmed')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'db_table': 'availability_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('provider', 'date', 'start_time')},
            },
        ),
    ]
