# Generated by Django 4.2.7 on 2026-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['date', 'time_slot'], 'verbose_name': 'Availability Slot', 'verbose_name_plural': 'Availability Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (8am - 12pm)'), ('afternoon', 'Afternoon (12pm - 4pm)'), ('evening', 'Evening (4pm - 8pm)')], db_index=True, default='morning', help_text='Time slot for the availability', max_length=10),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('provider', 'date', 'time_slot')},
        ),
    ]
