# Generated by Django 4.2.7 on 2026-01-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_availabilityslot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='start_time',
        ),
    ]
