# Generated by Django 4.2.7 on 2026-01-13 21:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_request_5c6215_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requested_datetime',
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 1, 13), help_text='Requested service date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (8am - 12pm)'), ('afternoon', 'Afternoon (12pm - 4pm)'), ('evening', 'Evening (4pm - 8pm)')], default='morning', help_text='Preferred time slot', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Service duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['requested_date', 'status'], name='bookings_request_ab884f_idx'),
        ),
    ]
